version: '3'
services:
  db:
    container_name: db
    image: postgres:16
    networks:
      - replyai-net
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/psql_init.sh:/docker-entrypoint-initdb.d/psql_init.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - replyai-net
    command: >
      redis-server --port 6379 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  evolution-api:
    container_name: evolution_api
    image: evoapicloud/evolution-api
    networks:
      - replyai-net
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances

  replyai-api:
    container_name: replyai_api
    build: .
    image: replyai-api:latest
    networks:
      - replyai-net
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      APP_MODE: api
    ports:
      - "8000:8000"

  replyai-worker:
    container_name: replyai_worker
    image: replyai-api:latest
    networks:
      - replyai-net
    depends_on:
      - replyai-api
      - redis
    restart: always
    env_file:
      - .env
    environment:
      APP_MODE: worker

volumes:
  evolution_store:
  evolution_instances:
  redis_data:
  pgdata:

networks:
  replyai-net:
    name: replyai-net
    driver: bridge