version: '3'
services:
  db:
    container_name: db
    image: postgres:16
    networks:
      - replyai-net
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: evolutionapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - replyai-net
    command: >
      redis-server --port 6379 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  evolution-api:
    container_name: evolution_api
    image: evoapicloud/evolution-api
    networks:
      - replyai-net
    depends_on:
      - redis
      - db
    restart: always
    env_file:
      - evolutionapi.env
    environment:
      DATABASE_CONNECTION_URI: postgresql://postgres:root@db:5432/evolutionapi?schema=public
    ports:
      - "8080:8080"
    volumes:
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances

  replyai-api:
    container_name: replyai_api
    build: .
    image: replyai-api:latest
    networks:
      - replyai-net
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:root@db:5432/postgres
    ports:
      - "8000:8000"

  replyai-worker:
    container_name: replyai_worker
    image: replyai-api:latest
    networks:
      - replyai-net
    depends_on:
      - replyai-api
      - redis
    restart: always
    command: python -m app.queue.worker
    env_file:
      - .env

volumes:
  evolution_store:
  evolution_instances:
  redis_data:
  pgdata:

networks:
  replyai-net:
    name: replyai-net
    driver: bridge