"""Initial migration

Revision ID: 3c364ed46198
Revises:
Create Date: 2026-01-19 14:38:00.908981

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c364ed46198"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("ai_reply_error_message", sa.String(), nullable=True),
        sa.Column(
            "message_client_type",
            sa.Enum("digisac", "evolution", name="messageclienttypeenum"),
            nullable=True,
        ),
        sa.Column(
            "agenda_client_type",
            sa.Enum("outlook", "google_calendar", name="agendaclienttypeenum"),
            nullable=True,
        ),
        sa.Column(
            "crm_client_type",
            sa.Enum("rdstation", name="crmclienttypeenum"),
            nullable=True,
        ),
        sa.Column(
            "financial_client_type",
            sa.Enum("asaas", name="financialclienttypeenum"),
            nullable=True,
        ),
        sa.Column("recall_timeout_minutes", sa.Integer(), nullable=True),
        sa.Column("final_recall_timeout_minutes", sa.Integer(), nullable=True),
        sa.Column("recall_quantity", sa.Integer(), nullable=True),
        sa.Column("recall_is_active", sa.Boolean(), nullable=False),
        sa.Column("confirmation_recall_is_active", sa.Boolean(), nullable=False),
        sa.Column("agenda_starting_time", sa.Time(), nullable=True),
        sa.Column("agenda_ending_time", sa.Time(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column(
            "event_cancellation_type",
            sa.Enum("keep", "delete", name="eventcancellationtypeenum"),
            nullable=True,
        ),
        sa.Column("appointment_duration_in_minutes", sa.Integer(), nullable=True),
        sa.Column("appointment_confirmation_is_active", sa.Boolean(), nullable=False),
        sa.Column("charge_due_payments", sa.Boolean(), nullable=False),
        sa.Column("send_due_payments_on_charge", sa.Boolean(), nullable=False),
        sa.Column("charge_due_payments_is_active", sa.Boolean(), nullable=False),
        sa.Column("openai_api_key", sa.String(), nullable=True),
        sa.Column("elevenlabs_api_key", sa.String(), nullable=True),
        sa.Column("default_assistant_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(op.f("ix_companies_id"), "companies", ["id"], unique=False)
    op.create_index(op.f("ix_companies_slug"), "companies", ["slug"], unique=False)
    op.create_table(
        "voices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("voice_name", sa.String(), nullable=True),
        sa.Column("elevenlabs_voice_id", sa.String(), nullable=False),
        sa.Column("stability", sa.Float(), nullable=True),
        sa.Column("similarity_boost", sa.Float(), nullable=True),
        sa.Column("style", sa.Float(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_voices_id"), "voices", ["id"], unique=False)
    op.create_table(
        "assistants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assistant_name", sa.String(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("shortcut", sa.String(), nullable=True),
        sa.Column("voice_id", sa.Integer(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(["voice_id"], ["voices.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assistants_id"), "assistants", ["id"], unique=False)
    sa.ForeignKeyConstraint(
        ["default_assistant_id"],
        ["assistants.id"],
    ),
    op.create_table(
        "threads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.String(), nullable=True),
        sa.Column(
            "last_message_from",
            sa.Enum("assistant", "customer", name="lastmessagefromenum"),
            nullable=False,
        ),
        sa.Column("contact_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_threads_id"), "threads", ["id"], unique=False)
    op.create_index(
        op.f("ix_threads_thread_id"), "threads", ["thread_id"], unique=False
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contact_id", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("contact_name", sa.String(), nullable=True),
        sa.Column("current_thread_id", sa.Integer(), nullable=True),
        sa.Column("current_assistant", sa.Integer(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(), nullable=True),
        sa.Column("recall_count", sa.Integer(), nullable=True),
        sa.Column("under_appointment_confirmation", sa.Boolean(), nullable=True),
        sa.Column("receive_ai_replies", sa.Boolean(), nullable=True),
        sa.Column("awaiting_human_contact", sa.Boolean(), nullable=True),
        sa.Column("deal_id", sa.String(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_assistant"],
            ["assistants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_thread_id"],
            ["threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contacts_contact_id"), "contacts", ["contact_id"], unique=False
    )
    op.create_index(op.f("ix_contacts_id"), "contacts", ["id"], unique=False)
    sa.ForeignKeyConstraint(
        ["contact_id"],
        ["contacts.id"],
    ),
    op.create_table(
        "agendas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("shortcut", sa.String(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agendas_id"), "agendas", ["id"], unique=False)
    op.create_table(
        "asaas_clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("client_number", sa.Integer(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_asaas_clients_id"), "asaas_clients", ["id"], unique=False)
    op.create_table(
        "digisac_clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("digisac_slug", sa.String(), nullable=True),
        sa.Column("service_id", sa.String(), nullable=True),
        sa.Column("digisac_token", sa.String(), nullable=True),
        sa.Column("default_user_id", sa.String(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_digisac_clients_id"), "digisac_clients", ["id"], unique=False
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("nickname", sa.String(), nullable=True),
        sa.Column("department_name", sa.String(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employees_id"), "employees", ["id"], unique=False)
    op.create_table(
        "evolutionapi_clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=True),
        sa.Column("instance_name", sa.String(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evolutionapi_clients_id"), "evolutionapi_clients", ["id"], unique=False
    )
    op.create_table(
        "googlecalendar_clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("access_token", sa.String(), nullable=True),
        sa.Column("refresh_token", sa.String(), nullable=True),
        sa.Column("expires_in", sa.Integer(), nullable=True),
        sa.Column("client_email", sa.String(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_googlecalendar_clients_id"),
        "googlecalendar_clients",
        ["id"],
        unique=False,
    )
    op.create_table(
        "medias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("mediatype", sa.String(), nullable=True),
        sa.Column("media_name", sa.String(), nullable=True),
        sa.Column("shortcut", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_medias_id"), "medias", ["id"], unique=False)
    op.create_table(
        "outlook_clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("access_token", sa.String(), nullable=True),
        sa.Column("refresh_token", sa.String(), nullable=True),
        sa.Column("expires_in", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.Float(), nullable=True),
        sa.Column("default_user", sa.String(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outlook_clients_id"), "outlook_clients", ["id"], unique=False
    )
    op.create_table(
        "rdstation_clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("default_source_id", sa.String(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rdstation_clients_id"), "rdstation_clients", ["id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("shortcut", sa.String(), nullable=True),
        sa.Column("contact_transfer_comment", sa.String(), nullable=True),
        sa.Column("digisac_department_id", sa.String(), nullable=True),
        sa.Column("digisac_user_id", sa.String(), nullable=True),
        sa.Column("is_confirmation_department", sa.Boolean(), nullable=True),
        sa.Column("digisac_client_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["digisac_client_id"],
            ["digisac_clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_departments_id"), "departments", ["id"], unique=False)
    op.create_table(
        "rdstation_deal_stages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shortcut", sa.String(), nullable=True),
        sa.Column("deal_stage_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("is_initial_deal_stage", sa.Boolean(), nullable=True),
        sa.Column("rdstationcrm_client_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rdstationcrm_client_id"], ["rdstation_clients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rdstation_deal_stages_id"),
        "rdstation_deal_stages",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_rdstation_deal_stages_id"), table_name="rdstation_deal_stages"
    )
    op.drop_table("rdstation_deal_stages")
    op.drop_index(op.f("ix_departments_id"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_rdstation_clients_id"), table_name="rdstation_clients")
    op.drop_table("rdstation_clients")
    op.drop_index(op.f("ix_outlook_clients_id"), table_name="outlook_clients")
    op.drop_table("outlook_clients")
    op.drop_index(op.f("ix_medias_id"), table_name="medias")
    op.drop_table("medias")
    op.drop_index(
        op.f("ix_googlecalendar_clients_id"), table_name="googlecalendar_clients"
    )
    op.drop_table("googlecalendar_clients")
    op.drop_index(op.f("ix_evolutionapi_clients_id"), table_name="evolutionapi_clients")
    op.drop_table("evolutionapi_clients")
    op.drop_index(op.f("ix_employees_id"), table_name="employees")
    op.drop_table("employees")
    op.drop_index(op.f("ix_digisac_clients_id"), table_name="digisac_clients")
    op.drop_table("digisac_clients")
    op.drop_index(op.f("ix_asaas_clients_id"), table_name="asaas_clients")
    op.drop_table("asaas_clients")
    op.drop_index(op.f("ix_agendas_id"), table_name="agendas")
    op.drop_table("agendas")
    op.drop_index(op.f("ix_voices_id"), table_name="voices")
    op.drop_table("voices")
    op.drop_index(op.f("ix_threads_thread_id"), table_name="threads")
    op.drop_index(op.f("ix_threads_id"), table_name="threads")
    op.drop_table("threads")
    op.drop_index(op.f("ix_contacts_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_contact_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_companies_slug"), table_name="companies")
    op.drop_index(op.f("ix_companies_id"), table_name="companies")
    op.drop_table("companies")
    op.drop_index(op.f("ix_assistants_id"), table_name="assistants")
    op.drop_table("assistants")
    # ### end Alembic commands ###
