#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<-EOSQL

    CREATE USER "$REPLYAI_PSQL_USER"
      WITH PASSWORD '$REPLYAI_PSQL_PASSWORD';

    CREATE DATABASE "$REPLYAI_PSQL_DB"
      OWNER "$POSTGRES_USER";

    CREATE USER "$EVOLUTIONAPI_PSQL_USER"
      WITH PASSWORD '$EVOLUTIONAPI_PSQL_PASSWORD';

    CREATE DATABASE "$EVOLUTIONAPI_PSQL_DB"
      OWNER "$POSTGRES_USER";

EOSQL

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$REPLYAI_PSQL_DB" <<-EOSQL

    GRANT CONNECT
      ON DATABASE "$REPLYAI_PSQL_DB"
      TO "$REPLYAI_PSQL_USER";

    GRANT USAGE, CREATE
      ON SCHEMA public
      TO "$REPLYAI_PSQL_USER";

    GRANT SELECT, INSERT, UPDATE, DELETE
      ON ALL TABLES IN SCHEMA public
      TO "$REPLYAI_PSQL_USER";

    GRANT USAGE, SELECT, UPDATE
      ON ALL SEQUENCES IN SCHEMA public
      TO "$REPLYAI_PSQL_USER";

EOSQL

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$EVOLUTIONAPI_PSQL_DB" <<-EOSQL

    GRANT CONNECT
      ON DATABASE "$EVOLUTIONAPI_PSQL_DB"
      TO "$EVOLUTIONAPI_PSQL_USER";

    GRANT USAGE, CREATE
      ON SCHEMA public
      TO "$EVOLUTIONAPI_PSQL_USER";

    GRANT SELECT, INSERT, UPDATE, DELETE
      ON ALL TABLES IN SCHEMA public
      TO "$EVOLUTIONAPI_PSQL_USER";

    GRANT USAGE, SELECT, UPDATE
      ON ALL SEQUENCES IN SCHEMA public
      TO "$EVOLUTIONAPI_PSQL_USER";

EOSQL