name: Deploy container to environments

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy-package:
    runs-on: ubuntu-latest
    environment: Test
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        app:
          - name: replyai-api-test
          - name: replyai-worker-test

    steps:
      - name: Login Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.REPLYAIAPITEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.REPLYAIAPITEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.REPLYAIAPITEST_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: ${{ matrix.app.name }}
          resourceGroup: replyai
          imageToDeploy: ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
          registryUrl: ghcr.io
          registryUsername: davidmrtns
          registryPassword: ${{ secrets.REPLYAIAPITEST_REGISTRY_PASSWORD }}
